# Site settings
title: interface.sg
email: hi@minitheory.com
description: "Write an awesome description for your new site here. The Earth was small, light blue, and so touchingly alone, our home that must be defended like a holy relic. The Earth was absolutely round. I believe I never knew what the word round meant until I saw Earth from space."
baseurl: ""
url: "http://interface.sg"
twitter_username: MinitheoryLLP
github_username:  Minitheory

# Build settings
markdown: kramdown
permalink: pretty
