# Site settings
title: interface.sg
email: hi@minitheory.com
description: "A guide to user experience design in Singapore."
baseurl: ""
url: "http://www.interface.sg"
twitter_username: MinitheoryLLP
github_username:  Minitheory

# Build settings
markdown: kramdown
permalink: pretty
